from django.urls import path
from cash_flow.views import (
    CashFlowRecordListView,
    CashFlowRecordUpdateView,
    CashFlowRecordDeleteView,
    CashFlowRecordCreateView,
    DirectoryView,
    StatusCreateView,
    StatusUpdateView,
    StatusDeleteView,
    TypeCreateView,
    TypeUpdateView,
    TypeDeleteView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    SubCategoryCreateView,
    SubCategoryUpdateView,
    SubCategoryDeleteView,
    load_subcategories,
    load_categories,
)
from cash_flow.apps import CashFlowConfig

app_name = CashFlowConfig.name

urlpatterns = [
    path("", CashFlowRecordListView.as_view(), name="cashflow_list"),
    path(
        "record/update/<int:pk>/",
        CashFlowRecordUpdateView.as_view(),
        name="cashflow_update"
    ),
    path(
        "record/delete/<int:pk>/",
        CashFlowRecordDeleteView.as_view(),
        name="cashflow_delete"
    ),
    path(
        "record/create/",
        CashFlowRecordCreateView.as_view(),
        name="cashflow_create"
    ),
    path(
        "directories/",
        DirectoryView.as_view(),
        name="directories"
    ),
    path(
        "status_create/",
        StatusCreateView.as_view(),
        name="status_create"
    ),
    path(
        "status_update/<int:pk>/",
        StatusUpdateView.as_view(),
        name="status_update"
    ),
    path(
        "status_delete/<int:pk>/",
        StatusDeleteView.as_view(),
        name="status_delete"
    ),
    path(
        "type_create/",
        TypeCreateView.as_view(),
        name="type_create"
    ),
    path(
        "type_update/<int:pk>/",
        TypeUpdateView.as_view(),
        name="type_update"
    ),
    path(
        "type_delete/<int:pk>/",
        TypeDeleteView.as_view(),
        name="type_delete"
    ),
    path(
        "category_create/",
        CategoryCreateView.as_view(),
        name="category_create"
    ),
    path(
        "category_update/<int:pk>/",
        CategoryUpdateView.as_view(),
        name="category_update"
    ),
    path(
        "category_delete/<int:pk>/",
        CategoryDeleteView.as_view(),
        name="category_delete"
    ),
    path(
        "subcategory_create/",
        SubCategoryCreateView.as_view(),
        name="subcategory_create"
    ),
    path(
        "subcategory_update/<int:pk>/",
        SubCategoryUpdateView.as_view(),
        name="subcategory_update"
    ),
    path(
        "subcategory_delete/<int:pk>/",
        SubCategoryDeleteView.as_view(),
        name="subcategory_delete"
    ),
    path(
        "ajax/load-subcategories/",
        load_subcategories,
        name='ajax_load_subcategories'
    ),
    path(
        "ajax/load-categories/",
        load_categories,
        name="load_categories"
    ),
]
