# Generated by Django 5.2.1 on 2025-05-31 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "категория", "verbose_name_plural": "категории"},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "статус", "verbose_name_plural": "статусы"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "подкатегория",
                "verbose_name_plural": "подкатегории",
            },
        ),
        migrations.AlterModelOptions(
            name="type",
            options={"verbose_name": "тип", "verbose_name_plural": "типы"},
        ),
    ]
