# Generated by Django 5.2.1 on 2025-05-31 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cash_flow", "0002_alter_category_options_alter_status_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashflowrecord",
            options={"verbose_name": "запись ДДС", "verbose_name_plural": "записи ДДС"},
        ),
    ]
